const plugin = require('tailwindcss/plugin')

module.exports = {
    content: ['./index.html', './src/**/*.vue'],
    theme: {
        extend: {
            colors: {
                primary: '#6750A4',
                'primary-container': '#EADDFF',
                secondary: '#625B71',
                'secondary-container': '#E8DEF8',
                tertiary: '#7D5260',
                'tertiary-container': '#FFD8E4',
                surface: '#FFFBFE',
                'surface-variant': '#E7E0EC',
                background: '#FFFBFE',
                error: '#B3261E',
                'error-container': '#F9DEDC',
                'on-primary': '#FFFFFF',
                'on-primary-container': '#21005E',
                'on-secondary': '#FFFFFF',
                'on-secondary-container': '#1E192B',
                'on-tertiary': '#FFFFFF',
                'on-tertiary-container': '#370B1E',
                'on-surface': '#1C1B1F',
                'on-surface-variant': '#49454E',
                'on-error': '#FFFFFF',
                'on-error-container': '#370B1E',
                'on-background': '#1C1B1F',
                outline: '#79747E',
                shadow: '#000000',
                'surface-tint-color': '#6750A4',
                'inverse-surface': '#313033',
                'inverse-on-surface': '#F4EFF4',
                'inverse-primary': '#D0BCFF',
                // primary: '#6750A4',
                // 'on-primary': '#FFFFFF',
                // 'primary-container': '#EADDFF',
                // 'on-primary-container': '#21005D',
                // secondary: '#625B71',
                // 'on-secondary': '#FFFFFF',
                // 'secondary-container': '#E8DEF8',
                // 'on-secondary-container': '#1D192B',
                // tertiary: '#7D5260',
                // 'on-tertiary': '#FFFFFF',
                // 'tertiary-container': '#FFD8E4',
                // 'on-tertiary-container': '#31111D',
                // error: '#B3261E',
                // 'on-error': '#FFFFFF',
                // 'error-container': '#F9DEDC',
                // 'on-error-container': '#410E0B',
                // outline: '#79747E',
                // background: '#FFFBFE',
                // 'on-background': '#1C1B1F',
                // surface: '#FFFBFE',
                // 'on-surface': '#1C1B1F',
                // 'surface-variant': '#E7E0EC',
                // 'on-surface-variant': '#49454F',
                // 'inverse-surface': '#313033',
                // 'inverse-on-surface': '#F4EFF4',
                // primary: '#4059aa',
                // 'on-primary': '#ffffff',
                // 'primary-container': '#dae1ff',
                // 'on-primary-container': '#001552',
                // secondary: '#595d71',
                // 'on-secondary': '#ffffff',
                // 'secondary-container': '#dde1f9',
                // 'on-secondary-container': '#161b2c',
                // tertiary: '#755470',
                // 'on-tertiary': '#ffffff',
                // 'tertiary-container': '#ffd6f7',
                // 'on-tertiary-container': '#2b1229',
                // error: '#ba1b1b',
                // 'on-error': '#ffffff',
                // 'error-container': '#ffdad4',
                // 'on-error-container': '#410001',
                // outline: '#75767f',
                // background: '#fefbff',
                // 'on-background': '#1b1b1f',
                // surface: '#fefbff',
                // 'on-surface': '#1b1b1f',
                // 'surface-variant': '#e2e2ed',
                // 'on-surface-variant': '#45464f',
                // 'inverse-surface': '#303033',
                // 'inverse-on-surface': '#f3f0f5',
            },
        },
    },
    plugins: [
        plugin(function ({ theme, addUtilities }) {
            const dectohex = (dec) => dec.toString(16).split('.')[0].padStart(2, '0')
            const tint = (opacity) => `${theme('colors.surface-tint-color')}${dectohex(256 * opacity)}`
            const tintGradient = (opacity) => `linear-gradient(to top, ${tint(opacity)}, ${tint(opacity)})`
            const tintedSurface = (opacity) => `${tintGradient(opacity)} ${theme('colors.surface')}`
            addUtilities(
                [0.05, 0.08, 0.11, 0.12, 0.14].reduce(
                    (utilities, opacity, index) => ({
                        ...utilities,
                        [`.bg-surface-${index + 1}`]: { background: tintedSurface(opacity) },
                    }),
                    {}
                )
            )
        }),
    ],
}
