module.exports = {
    content: ['./index.html', './src/**/*.vue'],
    theme: {
        extend: {
            colors: {
                primary: '#4059aa',
                'on-primary': '#ffffff',
                'primary-container': '#dae1ff',
                'on-primary-container': '#001552',
                secondary: '#595d71',
                'on-secondary': '#ffffff',
                'secondary-container': '#dde1f9',
                'on-secondary-container': '#161b2c',
                tertiary: '#755470',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#ffd6f7',
                'on-tertiary-container': '#2b1229',
                error: '#ba1b1b',
                'on-error': '#ffffff',
                'error-container': '#ffdad4',
                'on-error-container': '#410001',
                outline: '#75767f',
                background: '#fefbff',
                'on-background': '#1b1b1f',
                surface: '#fefbff',
                'on-surface': '#1b1b1f',
                'surface-variant': '#e2e2ed',
                'on-surface-variant': '#45464f',
                'inverse-surface': '#303033',
                'inverse-on-surface': '#f3f0f5',
            },
        },
    },
    plugins: [],
}
